language: python

services:
  - docker

env:
  global:
    - CONTAINER_TEST_IMAGE: ropod/allocation

before_install:
  - docker build -t $CONTAINER_TEST_IMAGE .
  - docker image ls

script:
  - docker run -d --name allocator $CONTAINER_TEST_IMAGE
  - docker exec -it allocator /bin/bash
  - python3 ../tests/task_allocator.py three_tasks.csv





