language: python

services:
  - docker


before_install:
  - docker-compose build task_allocation_test
  - docker image ls

install: skip

script:
  - docker-compose up -d mongo
  - docker-compose up -d ccu
  - docker-compose up -d robot
  - docker-compose up --exit-code-from task_allocation_test
after_script:
  - docker stop $(docker ps -aq)







