language: python

services:
  - docker

before_install:
  - docker build -t ropod-mrs:latest .
  - docker images
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag ropod-mrs:latest $DOCKER_USERNAME/ropod-mrs:latest
  - docker push $DOCKER_USERNAME/ropod-mrs:latest

install: skip

script:
  - docker-compose up --exit-code-from task_allocation_test task_allocation_test
  - docker-compose logs
after_script:
  - docker stop $(docker ps -aq)






