language: python

services:
  - docker


before_install:
  - docker-compose build task_allocation_test
  - docker image ls

install: skip

script:
  - docker-compose up --exit-code-from task_allocation_test task_allocation_test
  - docker-compose logs
after_script:
  - docker stop $(docker ps -aq)







