version: "2"

services:
  robot:
    container_name: robot
    image: ropod-mrs
    working_dir: /mrta/mrs/
    command: ["python3", "robot.py", "ropod_001", "non_intentional_delays", "non_overlapping_1.yaml"]
    network_mode: "host"
    tty: true
    stdin_open: true

  ccu:
    container_name: ccu
    image: ropod-mrs
    working_dir: /mrta/mrs/
    command: ["python3", "ccu.py", "non_intentional_delays", "non_overlapping_1.yaml"]
    network_mode: "host"
    tty: true
    stdin_open: true

  task_allocation_test:
    build: .
    container_name: task-mrs-test
    image: ropod-mrs
    working_dir: /mrta/mrs/experiments/
    command: ["python3", "run.py", "non_intentional_delays", "non_overlapping_1.yaml"]
    network_mode: "host"
    tty: true
    stdin_open: true
    depends_on:
      - robot
      - ccu


