version: "2"

services:
  mongo:
    container_name: mongo
    image: mongo:4.0-xenial
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"
    network_mode: "host"

  robot_1:
    container_name: robot_1
    image: ropod-mrs
    working_dir: /mrta/mrs/
    command: ["python3", "robot.py", "robot_001"]
    network_mode: "host"
    tty: true
    stdin_open: true
    depends_on:
      - mongo

  robot_2:
    container_name: robot_2
    image: ropod-mrs
    working_dir: /mrta/mrs/
    command: ["python3", "robot.py", "robot_002"]
    network_mode: "host"
    tty: true
    stdin_open: true
    depends_on:
      - mongo

  robot_3:
    container_name: robot_3
    image: ropod-mrs
    working_dir: /mrta/mrs/
    command: ["python3", "robot.py", "robot_003"]
    network_mode: "host"
    tty: true
    stdin_open: true
    depends_on:
      - mongo

  robot_4:
    container_name: robot_4
    image: ropod-mrs
    working_dir: /mrta/mrs/
    command: ["python3", "robot.py", "robot_004"]
    network_mode: "host"
    tty: true
    stdin_open: true
    depends_on:
      - mongo

  robot_5:
    container_name: robot_5
    image: ropod-mrs
    working_dir: /mrta/mrs/
    command: ["python3", "robot.py", "robot_005"]
    network_mode: "host"
    tty: true
    stdin_open: true
    depends_on:
      - mongo

  ccu:
    container_name: ccu
    image: ropod-mrs
    working_dir: /mrta/mrs/
    command: ["python3", "ccu.py"]
    network_mode: "host"
    tty: true
    stdin_open: true
    depends_on:
      - mongo

  task_allocation_test:
    build: .
    container_name: task-mrs-test
    image: ropod-mrs
    working_dir: /mrta/mrs/tests/
    command: ["python3", "allocate.py"]
    network_mode: "host"
    tty: true
    stdin_open: true
    depends_on:
      - mongo
      - ccu
      - robot_1
      - robot_2
      - robot_3
      - robot_4
      - robot_5
