version: "2"

services:
  mongo:
    container_name: mongo
    image: mongo:4.0-xenial
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"
    network_mode: "host"

  robot:
    container_name: robot
    image: ropod-mrs
    working_dir: /mrta/mrs/
    command: ["python3", "robot.py", "ropod_001"]
    network_mode: "host"
    tty: true
    stdin_open: true
    depends_on:
      - mongo

  ccu:
    container_name: ccu
    image: ropod-mrs
    working_dir: /mrta/mrs/
    command: ["python3", "ccu.py"]
    network_mode: "host"
    tty: true
    stdin_open: true
    depends_on:
      - mongo

  task_allocation_test:
    build: .
    container_name: task-mrs-test
    image: ropod-mrs
    working_dir: /mrta/mrs/tests/
    command: ["python3", "allocate.py"]
    network_mode: "host"
    tty: true
    stdin_open: true
    depends_on:
      - mongo
      - ccu
      - robot


