version: "2"

services:
  robot:
    container_name: robot
    image: ropod-mrs
    working_dir: /mrta/mrs/
    command: ["python3", "robot.py", "ropod_001"]
    network_mode: "host"
    tty: true
    stdin_open: true

  task_allocator:
    container_name: task-allocator
    image: ropod-mrs
    working_dir: /mrta/mrs/
    command: ["python3", "ccu.py"]
    network_mode: "host"
    tty: true
    stdin_open: true

  task_allocation_test:
    build: .
    container_name: task-mrs-test
    image: ropod-mrs
    working_dir: /mrta/tests/
    command: ["python3", "allocation_test.py"]
    network_mode: "host"
    tty: true
    stdin_open: true
    depends_on:
      - robot
      - task_allocator


