fleet:
    - ropod_001
    # - ropod_002
    # - ropod_003

task_allocation:
    bidding_rule: completion_time
    round_time: 10 # seconds
    stp_method: srea
    auctioneer: zyre_api # This is completely Zyre dependent
    request_alternative_timeslots: True

api:
  version: 0.1.0
  zyre:
    node_name: zyre_api
    interface: null
    groups:
      - TASK-ALLOCATION
    message_types:
      - TASK-ANNOUNCEMENT
      - BID
      - ALLOCATION
      - FINISH-ROUND
