ropods:
    ropod_001:
        id: ropod_001
#    ropod_002:
#        id: ropod_002
#    ropod_003:
#        id: ropod_003
#    ropod_004:
#        id: ropod_004
#    ropod_005:
#        id: ropod_005
bidding_rule: 1
auction_time: 10
zyre_group_name: ROPOD
task_allocator_zyre_params:
    groups: [TASK-ALLOCATION]
    message_types: [TASK-ANNOUNCEMENT, BID, NO-BID, ALLOCATION, SCHEDULE, REQUEST-SUGGESTION, SUGGESTION]
