version: 2
ccu_store:
  db_name: ropod_ccu_store
  port: 27017
resources:
  fleet:
    - ropod_001
    - ropod_002
    - ropod_003

plugins:
  task_allocation:
    bidding_rule:
      robustness: srea
      temporal: completion_time
    allocation_method: tessi
    round_time: 15 # seconds
    robot_proxies: true
    auctioneer: fms_zyre_api # This is completely Zyre dependent
    alternative_timeslots: True
    task_type: generic_task
    corrective_measure: re-allocate
    freeze_window: 300 # seconds
  task_monitor:
    task_type: ropod_task

robot_proxy:
  api:
    version: 0.1.0
    middleware:
      - zyre
    zyre:
      zyre_node:
        node_name: proxy
        interface: null
        groups:
          - TASK-ALLOCATION
          - ROPOD
        message_types: # Types of messages the node will listen to. Messages not listed will be ignored
          - TASK-ANNOUNCEMENT
          - ALLOCATION
      acknowledge: false
      publish:
        task:
          msg_type: 'TASK'
          groups: ['ROPOD', 'TASK-ALLOCATION'] # Optional, if not present will shout to all groups
          method: shout
        bid:
          msg_type: 'BID'
          groups: ['TASK-ALLOCATION']
          method: whisper
        finish-round:
          msg_type: 'FINISH-ROUND'
          groups: ['TASK-ALLOCATION']
          method: shout
      callbacks:
        - msg_type: 'TASK-ANNOUNCEMENT'
          component: 'bidder.task_announcement_cb'
        - msg_type: 'ALLOCATION'
          component: 'bidder.allocation_cb'


api:
  version: 0.1.0
  middleware:
    - zyre
  zyre:
    zyre_node:
      node_name: fms_zyre_api
      interface: null
      groups:
        - TASK-ALLOCATION
      message_types: # Types of messages the node will listen to. Messages not listed will be ignored
        - TASK
        - TASK-PROGRESS
        - BID
        - FINISH-ROUND
    acknowledge: false
    publish:
      task-announcement:
        msg_type: 'TASK-ANNOUNCEMENT'
        groups: ['TASK-ALLOCATION']
        method: shout
      allocation:
        msg_type: 'ALLOCATION'
        groups: ['TASK-ALLOCATION']
        method: shout
    callbacks:
      - msg_type: 'TASK'
        component: 'auctioneer.task_cb'
      - msg_type: 'BID'
        component: 'auctioneer.bid_cb'
      - msg_type: 'FINISH-ROUND'
        component: 'auctioneer.finish_round_cb'
      - msg_type: 'TASK-PROGRESS'
        component: 'task_monitor.task_progress_cb'

logger:
  version: 1
  formatters:
    default:
      format: '[%(levelname)-5.5s]  %(asctime)s [%(name)-25.25s] %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      class: ropod.utils.logging.color.ColorizingStreamHandler
      level: DEBUG
      formatter: default
      stream: ext://sys.stdout
    file:
      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      formatter: default
      filename: /var/log/ropod/fms/fms.log
      when: 'm'
      interval: 5
  loggers:
    requests:
      level: WARNING
      handlers: [console]
      propagate: no
    pyre:
      level: WARNING
      handlers: [console]
      propagate: no
    urllib3:
      level: WARNING
      handlers: [console]
      propagate: no
    OSMBridge:
      level: WARNING
      handlers: [console]
    OSMAdapter:
      level: WARNING
      handlers: [console]
    fms:
      level: DEBUG
  root:
    level: DEBUG
    handlers: [console, file]
