version: 2
ccu_store:
  db_name: ropod_ccu_store
  port: 27017
robot_store:
  db_name: ropod_store
  port: 27017
resource_manager:
  resources:
    fleet:
      - ropod_001
      - ropod_002
      - ropod_003

plugins:
  task_allocation:
    # Assuming we can have different types of tasks,
    # specify from where to import the Task and TaskStatus classes
    task_type:
      class: 'mrs.structs.task'
    allocation_method: tessi
    robot_proxies: true
    stp_solver: srea
  auctioneer:
    round_time: 5 # seconds
    alternative_timeslots: True
  dispatcher:
    freeze_window: 300 # seconds

robot_proxy:
  bidder:
    bidding_rule:
      robustness: srea  # has to be the same as the stp_solver
      temporal: completion_time
    auctioneer_name: fms_zyre_api # This is completely Zyre dependent
  schedule_monitor:
    corrective_measure: re-allocate
  api:
    version: 0.1.0
    middleware:
      - zyre
    zyre:
      zyre_node:
        node_name: proxy
        interface: null
        groups:
          - TASK-ALLOCATION
          - ROPOD
        message_types: # Types of messages the node will listen to. Messages not listed will be ignored
          - TASK-ANNOUNCEMENT
          - ALLOCATION
          - TIMETABLE
          - DELETE-TASK
        debug_msgs: false
      acknowledge: false
      publish:
        task:
          groups: ['ROPOD', 'TASK-ALLOCATION'] # Optional, if not present will shout to all groups
          msg_type: 'TASK'
          method: shout
        bid:
          groups: ['TASK-ALLOCATION']
          msg_type: 'BID'
          method: whisper
        finish-round:
          groups: ['TASK-ALLOCATION']
          msg_type: 'FINISH-ROUND'
          method: shout
      callbacks:
        - msg_type: 'TASK-ANNOUNCEMENT'
          component: 'bidder.task_announcement_cb'
        - msg_type: 'ALLOCATION'
          component: 'bidder.allocation_cb'
        - msg_type: 'TIMETABLE'
          component: '.timetable_cb'
        - msg_type: 'DELETE-TASK'
          component: '.delete_task_cb'

api:
  version: 0.1.0
  middleware:
    - zyre
    #- rest
    #- ros
  zyre:
    zyre_node:
      node_name: fms_zyre_api
      interface: null
      groups:
        - ROPOD
        - TASK-ALLOCATION
      message_types: # Types of messages the node will listen to. Messages not listed will be ignored
        - TASK-PROGRESS
        - BID
        - FINISH-ROUND
        - ALLOCATE-TASK
    acknowledge: false
    debug_messages:
      - 'TASK-REQUEST'
    publish:
      task-announcement:
        msg_type: 'TASK-ANNOUNCEMENT'
        groups: ['TASK-ALLOCATION']
        method: shout
      allocation:
        msg_type: 'ALLOCATION'
        groups: ['TASK-ALLOCATION']
        method: shout
    callbacks:
      - msg_type: 'ALLOCATE-TASK'
        component: 'auctioneer.allocate_task_cb'
      - msg_type: 'BID'
        component: 'auctioneer.bid_cb'
      - msg_type: 'FINISH-ROUND'
        component: 'auctioneer.finish_round_cb'
  rest:
    server:
      ip: 127.0.0.1
      port: 8081
    routes:
      - path: '/number'
        resource:
          module: 'fleet_management.api.rest.resources'
          class: 'RandomGenerator'
  ros:
    publishers:
      - topic: '/fms/task'
        msg_type: Task
        msg_module: ropod_ros_msgs.msg
    subscribers:
      - topic: '/fms/task_request'
        msg_type: TaskRequest
        msg_module: ropod_ros_msgs.msg
        callback: task_cb

logger:
  version: 1
  formatters:
    default:
      format: '[%(levelname)-5.5s]  %(asctime)s [%(name)-35.35s] %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      class: ropod.utils.logging.color.ColorizingStreamHandler
      level: DEBUG
      formatter: default
      stream: ext://sys.stdout
    file:
      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      formatter: default
      filename: /var/log/ropod/fms/fms.log
      when: 'm'
      interval: 5
  loggers:
    requests:
      level: WARNING
      handlers: [console]
      propagate: no
    pyre:
      level: WARNING
      handlers: [console]
      propagate: no
    urllib3:
      level: WARNING
      handlers: [console]
      propagate: no
    OSMBridge:
      level: WARNING
      handlers: [console]
    OSMAdapter:
      level: WARNING
      handlers: [console]
    fms:
      level: DEBUG
    mrs:
      level: DEBUG
  root:
    level: DEBUG
    handlers: [console, file]