fleet:
    - ropod_001
    # - ropod_002
    # - ropod_003

task_allocation:
    bidding_rule: 1
    auction_time: 10 # seconds
    scheduling_method: srea
    auctioneer: zyre_api # This is completely Zyre dependent

api:
  version: 0.1.0
  zyre:
    node_name: zyre_api
    interface: null
    groups:
      - TASK-ALLOCATION
    message_types:
      - BID
      - NO-BID
      - ALLOCATION
      - SCHEDULE
