fleet:
    - ropod_001
    # - ropod_002
    # - ropod_003

bidding_rule: 1
auction_time: 10
scheduling_method: srea

api:
  version: 0.1.0
  zyre:
    # node_name: zyre_api
    interface: null
    groups:
      - TASK-ALLOCATION
    message_types:
      - BID
      - NO-BID
      - ALLOCATION
      - SCHEDULE
