version: 1
formatters:
  default:
    format: '[%(levelname)-5.5s]  %(asctime)s [%(name)-25.25s] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
loggers:
  robot:
    level: DEBUG
  auctioneer:
      level: DEBUG
  task_requester:
      level: DEBUG
root:
  level: DEBUG
  handlers: [console]
